#!/bin/bash
set -e

WRAPPER=/usr/bin/apt-wrapper
APT=/usr/bin/apt
APT_GET=/usr/bin/apt-get

mv  /usr/bin/apt /usr/bin/apt.real
mv /usr/bin/apt-get /usr/bin/apt-get.real

ln -sf "$WRAPPER" "$APT"
ln -sf "$WRAPPER" "$APT_GET"


