#!/bin/bash
set -e

HPM_IMAGE_DIR="$HOME/.hpm/images"
export CONTAINERS_STORAGE_ROOT="$HOME/.hpm/containers"
export CONTAINERS_STORAGE_DRIVER=vfs

for tarball in "$HPM_IMAGE_DIR"/*.tar; do
    image_name=$(basename "$tarball" .tar)
    
    if ! podman image exists "$image_name"; then
        echo "[hpm] Loading container image: $image_name"
        podman load -i "$tarball"
    fi
done

