#! /bin/sh


lb config noauto \
	--distribution stable \
	--distribution-chroot stable \
	--distribution-binary stable \
	--parent-distribution stable \
	--parent-distribution-binary stable \
	--parent-distribution-chroot stable \
	--memtest memtest86+ \
	--bootloaders grub-efi \
	--binary-images iso \
	--checksums sha256 \
	--color \
	--debian-installer none \
	--image-name hoodos-live-grub_efi \
	--firmware-binary true \
	--firmware-chroot true 
	"${@}"
