#! /bin/sh


lb config noauto \
	--distribution bookworm \
	--distribution-chroot bookworm \
	--distribution-binary bookworm \
	--memtest memtest86+ \
	--bootloaders grub-efi \
	--binary-images iso \
	--checksums sha256 \
	--color \
	--debian-installer none \
	--image-name hoodos-live-grub_efi \
	--firmware-binary true \
	--firmware-chroot true 
	"${@}"
