[shell/extensions/quick-settings-tweaks]
datemenu-disable-menu=false
debug-show-layout-border=false
dnd-quick-toggle-indicator-position='system-tray'
media-enabled=true
media-progress-enabled=true
menu-animation-enabled=true
notifications-autohide=true
notifications-enabled=true
notifications-remove-shadow=true
notifications-show-scrollbar=false
notifications-use-native-controls=false
overlay-menu-enabled=false
system-indicator-privacy-indicator-style='monochrome'
system-indicator-screen-recording-indicator-use-accent=true
system-indicator-screen-sharing-indicator-use-accent=true
system-items-layout-enabled=true
system-items-layout-hide=false
toggles-layout-enabled=true
unsafe-quick-toggle-enabled=false
unsafe-quick-toggle-last-state=false
volume-mixer-fade-offset=0
volume-mixer-label-text='title'
volume-mixer-max-height=56
volume-mixer-menu-enabled=true
volume-mixer-show-icon=false
volume-mixer-show-scrollbar=false
weather-enabled=true

[shell/extensions/user-theme]
name='Firewatch-1'

[shell/extensions/vitals]
alphabetize=true
hide-icons=false
hide-zeros=false
hot-sensors=['temperature_avg', '_memory_usage_', '_processor_usage_', 'network-rx_max']
icon-style=1
menu-centered=false
position-in-panel=0
show-battery=false
show-fan=true
show-gpu=true
show-memory=true
show-network=true
show-processor=true
show-storage=true
show-system=true
show-temperature=true
show-voltage=true

[shell/keybindings]
show-screenshot-ui=['<Shift><Super>s']
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []
switch-to-application-5=@as []
switch-to-application-6=@as []
switch-to-application-7=@as []
switch-to-application-8=@as []
switch-to-application-9=@as []

[shell/weather]
automatic-location=true
locations=[<(uint32 2, <('Moscow', 'UUWW', true, [(0.97127572873484425, 0.65042604039431762)], [(0.97305983920281813, 0.65651530216830811)])>)>]

[shell/world-clocks]
locations=[<(uint32 2, <('Moscow', 'UUWW', true, [(0.97127572873484425, 0.65042604039431762)], [(0.97305983920281813, 0.65651530216830811)])>)>]

[software]
check-timestamp=int64 1762165940
first-run=false
flatpak-purge-timestamp=int64 1762173042

[tweaks]
show-extensions-notice=false
