settings:

  initialPartitioningChoice: erase
  allowManualPartitioning: false
  defaultFileSystemType: "ext4"
  availableFileSystemTypes: ["ext4"]

  encryption:
    enableLuks: true
    required: true
    luksCipher: "aes-xts-plain64"
    luksKeySize: 512
